# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: basic install
  shortDescription: AWS {SERVICE} controller is a service controller for managing {SERVICE} resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon {SERVICE}
description: |-
  Manage Amazon {SERVICE} resources in AWS from within your Kubernetes cluster.


  **About Amazon {SERVICE}**


  {ADD YOUR DESCRIPTION HERE}


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**. 
samples:
- kind: ExampleCustomKind
  spec: '{}'
- kind: SecondExampleCustomKind
  spec: '{}'
maintainers:
- name: "Your Team Name"
  email: "your-team@example.com"
links:
- name: Amazon {SERVICE} Developer Resources
  url: "{YOUR SERVICE DEVELOPER RESOURCES URL}"
